[package]
name = "ghl"
version = "0.6.0"
edition = "2021"

[dependencies]
colored = "2"
home = "0.5.9"
inquire = { version = "0.6.2", features = ["editor"] }
open = "5.1.2"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
